export const ANNOTATION_EDIT_GENERATION_TOOL = 'generate_image'
export const ANNOTATION_EDIT_MODEL = 'seedream/5-pro-reference-to-image'

export interface ImageAnnotationReference {
  url: string
  name: string
}

export interface ImageAnnotationPoint {
  x: number
  y: number
  text: string
  references?: ImageAnnotationReference[]
}

export interface ImageAnnotationEdit {
  imageUrl: string
  points: ImageAnnotationPoint[]
  annotatedImageUrl?: string
}

function validProjectMediaUrl(value: string) {
  if (/^https?:\/\//i.test(value)) {
    try {
      const url = new URL(value)
      return !url.username && !url.password
    }
    catch {
      return false
    }
  }
  if (!value.startsWith('/media/') || value.startsWith('//') || value.includes('?') || value.includes('#') || value.includes('\\'))
    return false
  try {
    const key = decodeURIComponent(value.slice('/media/'.length))
    return Boolean(key)
      && !/\p{Cc}/u.test(key)
      && key.split('/').every(part => Boolean(part) && part !== '.' && part !== '..' && !part.startsWith('.'))
  }
  catch {
    return false
  }
}

export function validateImageAnnotationEdit(value: unknown, allowedUrls: string[]): ImageAnnotationEdit {
  const edit = value as ImageAnnotationEdit | undefined
  if (!edit || typeof edit.imageUrl !== 'string' || !allowedUrls.includes(edit.imageUrl))
    throw new Error('Select a source image from this conversation.')
  if (!Array.isArray(edit.points) || edit.points.length < 1 || edit.points.length > 16)
    throw new Error('Add between 1 and 16 annotation points.')
  const points = edit.points.map((point) => {
    if (!point || !Number.isInteger(point.x) || !Number.isInteger(point.y) || point.x < 0 || point.x > 1000 || point.y < 0 || point.y > 1000)
      throw new Error('Invalid annotation position.')
    if (typeof point.text !== 'string' || !point.text.trim() || point.text.trim().length > 1000)
      throw new Error('Describe each edit in 1–1000 characters.')
    if (point.references !== undefined && (!Array.isArray(point.references) || point.references.length > 14))
      throw new Error('Use up to 14 reference images per point.')
    const references = (point.references || []).map((reference) => {
      if (!reference || typeof reference.url !== 'string' || reference.url.length > 2000 || !validProjectMediaUrl(reference.url) || typeof reference.name !== 'string' || !reference.name.trim() || reference.name.length > 100)
        throw new Error('Select each referenced image from the project list.')
      return { url: reference.url, name: reference.name.trim() }
    })
    return {
      x: point.x,
      y: point.y,
      text: point.text.trim(),
      ...(references.length ? { references } : {}),
    }
  })
  // annotatedImageUrl is generated by the server and is never accepted from clients.
  return { imageUrl: edit.imageUrl, points }
}

export function annotationMarkersSvg(points: ImageAnnotationPoint[], width: number, height: number) {
  const radius = Math.max(10, Math.min(width, height) * 0.018)
  const markers = points.map((point, index) => {
    const x = point.x / 1000 * width
    const y = point.y / 1000 * height
    const cx = Math.max(radius + 2, Math.min(width - radius - 2, x))
    const cy = Math.max(radius + 2, Math.min(height - radius - 2, y))
    return `<line x1="${x}" y1="${y}" x2="${cx}" y2="${cy}" stroke="#fff" stroke-width="2"/><circle cx="${cx}" cy="${cy}" r="${radius}" fill="#e11d48" stroke="#fff" stroke-width="2"/><text x="${cx}" y="${cy}" dy=".35em" text-anchor="middle" font-family="sans-serif" font-size="${radius}" font-weight="700" fill="#fff">${index + 1}</text>`
  }).join('')
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">${markers}</svg>`
}
